version: "3.7"

services: 
  db: 
    image: postgres
    container_name: carford-postgresql 
    environment:
      POSTGRES_PASSWORD: example
    restart: always
  sw:

    container_name: carford-software
    restart: always
    ports:
      - "80:8501"
      - "5000:5000"
    depends_on:
      - db
       