FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000


CMD python config_inicial.py ; gunicorn --bind 0.0.0.0:5000 app:app

